- Day 02
- Date: 12 june, 2026
- Topics practiced: Numpy

========= Numpy ==========

In [7]:
import numpy as np

### Creating array list

In [10]:
ar_1d = np.array([1, 2, 3, 4, 5])
print("1D array :", ar_1d)

ar_2d = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print("2D array :", ar_2d)

1D array : [1 2 3 4 5]
2D array : [[1 2 3 4 5]
 [1 2 3 4 5]]


### List vs Numpy

In [14]:
py_list = [1, 2, 3]
print("python list multiplication",py_list * 2)

np_array = np.array([1, 2, 3]);
print("python list multiplication",np_array * 2)
#element wise multiplication in numpy


import time
start = time.time();
py_list = [i * 2 for i in range(1000000)]
print("\nList operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\nNumpy operation time: ", time.time() - start)



python list multiplication [1, 2, 3, 1, 2, 3]
python list multiplication [2 4 6]

List operation time:  0.08510875701904297

Numpy operation time:  0.0071299076080322266


### creating array from scratch

In [23]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
print("Ones array: \n", ones)

full = np.full((2, 2), 10)
print("full array: \n", full)


random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[10 10]
 [10 10]]
random array: 
 [[0.39635354 0.58130679 0.98411538]
 [0.27415185 0.53809231 0.28433627]]
sequence array: 
 [0 2 4 6 8]


### vector, Matrix and Tensor

In [27]:
vector = np.array([1, 2, 3])
print("Vector : ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("matrix : \n", matrix)


tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]],
                   [[9, 10], [11, 12]]])
print("Tensor : \n", tensor)


Vector :  [1 2 3]
matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor : 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Array Properties

In [ ]:
ar = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape",ar.shape)
print("Dimention:",ar.ndim)
print("Size:",ar.size)
print("Data type:",ar.dtype)

Shape (2, 3)
Dimention: 2
Size: 6
Data type: int64


### Array Reshaping

In [41]:
ar = np.arange(15)
print("Original array", ar)


reshaped = ar.reshape((3, 5))
print("Reshaped array", reshaped)

#returns the copy
flattened = reshaped.flatten()
print("flattened array", flattened)

#returns original array instead of copy
raveled = reshaped.ravel()
print("Raveled array", raveled)


#transpose
transpose = reshaped.T
print("Transposed ", transpose)


Original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reshaped array [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Transposed  [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Numpy array Operations

In [42]:
import numpy as np

In [43]:
ar = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])
print("Basic slicing",ar[2:7])
print("With step",ar[1:8:2])
print("Negative indexing", ar[-3])

Basic slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 8


In [46]:
ar_2d = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [8, 9, 10]])

print("Specific", ar_2d[1, 2])
print("Entire row: ", ar_2d[1])
print("Entire col: ", ar_2d[:,1])


Specific 6
Entire row:  [4 5 6]
Entire col:  [2 5 9]


### Sorting

In [115]:
unsorted = np.array([2, 1, 5, 2, 5, 6, 3])
print("Sorted array:" , np.sort(unsorted))

ar_2d_unsorted = np.array([[11, 1, 6],
                        [10, 9, 5],
                        [7, 6, 8]])
print("Sorted 2D array by column\n", np.sort(ar_2d_unsorted,axis = 1)) #axis 0 = column by, axis 1 = row by sort




Sorted array: [1 2 2 3 5 5 6]
Sorted 2D array by column
 [[ 1  6 11]
 [ 5  9 10]
 [ 6  7  8]]


### Filter

In [62]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers", even_numbers)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [69]:
#we can store expression as mask and use it to filter array
mask = numbers > 5
print("Mask ", mask)
print("Numbers greater than 5 ", numbers[mask])

Mask  [False False False False False  True  True  True  True  True]
Numbers greater than 5  [ 6  7  8  9 10]


## Fency indexing vs np. where()


In [70]:
#we can pass index array into another array and get elements of those arrays
indices = [0, 2, 4]
print(numbers[indices])

## mash store using where
where_result = np.where(numbers > 5) 
print("Where result ", where_result)
print("Np where", numbers[where_result])

[1 3 5]
Where result  (array([5, 6, 7, 8, 9]),)
Np where [ 6  7  8  9 10]


In [75]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

#we can think as if else
# if(numbers > 5):
#     numbers * 2
# else:
#      numbers


[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [79]:
ar = np.array([1, 2, 3, 4])
br = np.array([4, 5, 6,6])

sum = ar + br
print("sum: ",sum)


combined = np.concatenate((ar,br))
print("Merged: ", combined)

sum:  [ 5  7  9 10]
Merged:  [1 2 3 4 4 5 6 6]


### Array Compatibility

In [83]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes: ", a.shape == b.shape and b.shape == c.shape)


Compatibility shapes:  True


In [94]:



original = np.array([[1, 2], [3, 4]])
#Adding new row using vstack = vertical stack
new_row = np.array([5, 6])
updated_original = np.vstack((original, new_row)) 
print(original);
print(updated_original)

# #adding new col using hstack = horizontal stack
new_col = np.array([[7], [8]])
updated_original = np.hstack((original, new_col))
print(updated_original)




[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


### Deleting

In [ ]:
ar = np.array([1, 2, 3, 5, 6])
deleted = np.delete(ar, 2) #returns full array after delete
#we can give specific index or slicing of array
print(deleted)

[1 2 5 6]


## Practice


In [107]:
import numpy as np
import matplotlib.pyplot as plt
#Data structure: [resturant id, 2021, 2022, 2023, 2024] sells data
sales_data = np.array([
    [1, 150000, 180000, 250000, 280000], #paradise biriyani
    [2, 120000, 130000, 140000, 270000], #Beijing bites
    [3, 180000, 210000, 270000, 250000], #Pizza hub
    [4, 200000, 230000, 250000, 260000], #Burger Point
    [5, 160000, 205000, 230000, 240000]  #Chai point
])

print("========== Restaurant Sells analysis ===========")
print("\n Sales date shape ", sales_data.shape)

print("\nSample data for first three restaurnt \n", sales_data[0:3]) #used slice for first three restaurant





========== Restaurant Sells analysis ===========

 Sales date shape  (5, 5)

Sample data for first three restaurnt 
 [[     1 150000 180000 250000 280000]
 [     2 120000 130000 140000 270000]
 [     3 180000 210000 270000 250000]]


In [114]:
# Total yearly sales
print("Yearly sales: ", np.sum(sales_data[:,1:],axis=0))


# Minimum sales per restaurant
min_sales = np.min(sales_data[:,1:], axis=1)
print("Min sales: ", min_sales)

Yearly sales:  [ 810000  955000 1140000 1300000]
Min sales:  [150000 120000 180000 200000 160000]
